/* The page guides behind `?`: the prototype's GUIDES (calm.ly-workforce-v15.html:
   9930-10060). What belongs here is how a page fits together, what it will
   and will not do. Anything about current state or the consequence of an
   action stays on the page, where it can be seen. Copy is the prototype's,
   with each em-dash aside rewritten as its own sentence. A page whose view
   has no entry shows no `?`. */
export interface Guide { label: string; title: string; sections: readonly (readonly [string, string])[] }

export const GUIDES: Readonly<Record<string, Guide>> = {
  ts: { label: 'How time capture works', title: 'How time capture works', sections: [
    ['Clocking',
      'Clock in when you start and out when you finish. Your times fill in and lock while the shift runs, and breaks are recorded as you take them.'],
    ['Manual entry',
      'The day form and the weekly grid capture the same fields. The grid pivots them across the week for people who record a whole week at once. Fields marked required are required for your employee type.'],
    ['Breaks and allowances',
      'Add breaks only if you took them. They come off your net hours. Tick any allowances that applied to the shift. Rates are held in Business Central; nothing here sets a monetary value.'],
    ['What is checked',
      'Overlapping breaks, a break outside the shift, breaks longer than the shift and a day above the daily maximum are refused. Long days, short rest and hours away from your rota line are flagged for your approver but still submit.'],
    ['After you submit',
      'It goes to your manager. If it comes back, correct it and submit again. That is recorded as a resubmission rather than a new entry.'],
    ['The full key',
      'Status: approved, submitted, resubmitted, draft, sent back, and nothing recorded on a day you were rota’d. Leave and sickness show with a padlock, because they block capture while leave blocks the timesheet.'],
  ] },
  tteam: { label: 'How to read this queue', title: 'How to read this queue', sections: [
    ['What is waiting',
      'The queue holds first submissions and resubmissions together, so a corrected entry cannot fall out of sight. A resubmission carries the reason it was sent back.'],
    ['Why a row is flagged',
      'A day over the review threshold, a large variance against the rota line, short rest, or an entry made by a manager on somebody else’s behalf.'],
    ['The posting dot',
      'Hollow means not sent yet. Amber means queued for Business Central. Filled means the dispatcher posted it. In this build that posting is simulated, not a Business Central confirmation.'],
    ['Approving in bulk',
      'Approve all is scoped to your location and asks you to confirm the record count, the hours and any exceptions first. Each approval queues its own posting.'],
  ] },
  trota: { label: 'Where shifts come from', title: 'Where shifts come from', sections: [
    ['1 · Working patterns build the backbone',
      'Admin sets a pattern once, for example 4-on / 4-off nights, and the rota is generated from it up to the horizon. Most shifts arrive this way, carrying the pattern’s cost centre, location and job profile.'],
    ['2 · Each location sets how many people a shift needs',
      'A location’s support level sets the people it needs on every shift. Anything below that shows as a red gap and, while Rota setup says so, blocks publishing.'],
    ['3 · You add, change and remove shifts',
      'Tap an empty cell on any row to add a shift for that person. Tap a shift to change or remove it. Drag a shift from the palette onto a cell, or pick one up with Enter and put it down on a cell with Enter. Use “Add an extra shift” when you need more people than the minimum.'],
    ['4 · Filling a gap: assign, suggest, or advertise',
      'Assign someone directly, ask calm.ly to suggest who fits, or open a cover request so eligible colleagues and bank workers are notified in configured stages.'],
    ['5 · Leave and sickness feed straight in',
      'Approved leave and sickness show on the rota and count against the day’s cover. Change them on Team leave or the Sickness tab, not here.'],
    ['Removing a shift that takes a day below the minimum opens a cover request by itself',
      'Coverage is recalculated on every change, not on a schedule. A change to a published week is recorded as an amendment and the week must be republished.'],
  ] },
  mts: { label: 'What the capture rules do', title: 'What the capture rules do', sections: [
    ['Errors block, thresholds warn',
      'The settings on this page decide what is refused outright and what is merely flagged for the approver.'],
    ['Always refused, whatever these are set to',
      'Overlapping breaks, a break outside the shift, breaks longer than the shift, a break with only one end, and a net total below the minimum. These are integrity rules, not policy.'],
    ['Where they apply',
      'Every path that writes time: the day form, the weekly grid, proxy entry on behalf of somebody else, and week submission.'],
  ] },
  tshifts: { label: 'What a shift type is', title: 'What a shift type is', sections: [
    ['One definition, used everywhere',
      'A shift carries a code, its times, an unpaid break and a colour. Paid hours, whether it crosses midnight and how it appears on the grid all follow from those times. Nothing is entered twice.'],
    ['It is tenant-wide',
      'Adding or changing a shift affects every location. Existing rota days keep the shift and have their hours recalculated, which is why a change is audited.'],
    ['Night shifts',
      'A shift flagged as a night shift is only offered to people whose employee type permits night work and who hold the training for it.'],
    ['Removing one',
      'A shift still used on a rota day or in a working pattern cannot be removed until those uses are cleared.'],
  ] },
  tpat: { label: 'How patterns fill a rota', title: 'How patterns fill a rota', sections: [
    ['A repeating cycle',
      'Set which day of the cycle carries which shift, attach the locations and job profiles it runs at, then add people with an offset each so they stagger across the cycle.'],
    ['Generating',
      'Generating writes rota lines forward to the horizon. It never overwrites a cell that already holds a shift, leave or sickness, and it skips weeks that are already published. Both are reported rather than applied silently.'],
    ['What is checked',
      'Rest between the days it writes is checked against the employee type’s rule and reported. Clearance, qualifications and maximum hours are evaluated when the week is opened.'],
  ] },
  mrota: { label: 'How the rota is built', title: 'How the rota is built', sections: [
    ['Three ways to fill a week',
      'Copy last week brings the previous week forward. Repeat forward repeats the week on screen for a chosen number of weeks. A working pattern generates from a repeating cycle across a long horizon.'],
    ['What none of them will do',
      'Overwrite a cell that already holds a shift, leave or sickness, or write into a week that is already published. Those are reported rather than silently applied.'],
    ['Publishing',
      'A week moves Draft → Review → Published. Changing a published week makes it an Amendment, records who changed what, and requires republishing before colleagues see it.'],
    ['Who may build it',
      'A tenant policy above the permission matrix. The matrix decides whether a persona could hold the capability; the policy decides whether the tenant allows it. Both must agree.'],
    ['Reading the grid',
      'Each cell carries the shift code and its times. The key under the grid lists only the shifts actually on this week, with a count of each, plus leave, sickness and how many cells are still unassigned.'],
  ] },
  mleave: { label: 'How leave reaches the rota', title: 'How leave reaches the rota', sections: [
    ['Leave → Rota → Cover, in one chain',
      'Approving a request marks the person unavailable, recalculates coverage for those days, and raises a cover request where the shortfall breaches minimum staffing.'],
    ['Entitlement',
      'Calculated from the shared workforce record: policy, contracted hours and working pattern. Change any of the three and entitlement recalculates.'],
  ] },
  notices: { label: 'How notices work', title: 'How notices work', sections: [
    ['What you see here',
      'Notices from your organisation and your location. Urgent and pinned notices come first. A notice moves to Expired after its end date.'],
    ['Acknowledging',
      'Some notices ask you to acknowledge them. That records that you read this version, with the date and time, and whoever posted it can see it.'],
    ['When a notice changes',
      'If the text changes after you acknowledged it, it becomes a new version and you are asked again. Your earlier acknowledgement stays on record.'],
  ] },
  tnotices: { label: 'How posting works', title: 'How posting works', sections: [
    ['Who you can reach',
      'A manager posts to the location they work at, or to a department within it. Posting to everyone, or to any location, needs Post notices to everyone.'],
    ['Drafts, live and withdrawn',
      'A draft is seen by nobody and can be deleted. Once live, a notice cannot be deleted. Withdraw it with a reason and it leaves colleagues’ view but stays on record.'],
    ['Editing a live notice',
      'Changing the title or text makes a new version and asks everyone to acknowledge again. Dates, pin and urgency change without a new version. The audience is fixed once live.'],
    ['What is recorded',
      'Posting, every edit, pinning, withdrawing and each acknowledgement go to the audit log with who, what and before and after.'],
  ] },
  /* 1c group 8: the 1b and 1c pages the prototype gives a guide (v15:9931-10058) */
  apeople: { label: 'How the workforce record works', title: 'How the workforce record works', sections: [
    ['One record per person, used by every module',
      'Employee ID, employee type, job profile, department, location, contracted hours and clearance are held once here. Timesheet entries, rota shifts and leave requests reference this record; they never copy it.'],
    ['What that means in practice',
      'Move somebody to another location and the rota, coverage and eligibility follow on the next screen. There is no second list to keep in step.'],
  ] },
  aloc: { label: 'How dimensions are shared', title: 'How dimensions are shared', sections: [
    ['One job profile list, three consumers',
      'Held once here and referenced by every module. There is no second copy anywhere.'],
    ['Locations, departments and cost centres',
      'The same rule applies. A location carries its support level and minimum staffing, which the rota reads directly when it calculates coverage.'],
  ] },
  acon: { label: 'How contracted hours are used', title: 'How contracted hours are used', sections: [
    ['Contracted hours are shared, not module-specific',
      'Rota compares scheduled hours against them, Timesheet compares actual hours against them, and Leave pro-rates entitlement from them. Changing one here changes all three.'],
    ['Bank and zero-hours colleagues',
      'A colleague with no contracted baseline is measured against a maximum rather than a target, so the hours position shows a ceiling instead of a variance.'],
  ] },
  /* The prototype's second section said its checks ran in the browser; here
     the server refuses every request a capability does not allow, so the
     section says that, and keeps its heading. */
  aperm: { label: 'How permissions work', title: 'How permissions work', sections: [
    ['These switches are live',
      'The navigation is rendered from this matrix. Revoke a capability and the surface it names disappears for that persona, and the action behind it is refused.'],
    ['UI visibility is not security',
      'Hiding a button is not the same as refusing the request behind it. The server checks every capability as well, so a request the matrix does not allow is refused even when it does not come from this screen.'],
    ['Tenant policy can sit above the matrix',
      'A capability can also be withheld by a tenant setting, such as “Who builds the rota” under Rota. Where both apply, both must agree.'],
  ] },
  docs: { label: 'Where documents come from', title: 'Where documents come from', sections: [
    ['Read-only outputs from payroll',
      'Payslips, P45 and P60 are produced by payroll in Business Central. Workforce shows them when the payroll integration is live; it never generates or alters them.'],
    ['Everything else',
      'Contracts, policies and certificates are held here and can carry an expiry. An expiring compliance document surfaces as an exception for your manager before it lapses.'],
  ] },
  profile: { label: 'What is held where', title: 'What is held where', sections: [
    ['Pay and payroll documents are read-only outputs',
      'Salary, payslips, P45 and P60 are owned by payroll in Business Central. Workforce shows them when the payroll integration is live; it never sets a monetary value.'],
    ['What you can change yourself',
      'Contact, emergency and bank details are yours to propose. Everything above them is set by HR and comes from the shared workforce record.'],
    ['A change is a request',
      'It is approved before it takes effect, and the old value is kept in the audit trail.'],
  ] },
};
