/* Copies the prototype's token layer verbatim. The prototype is the source of
   truth for the calm.ly design language, so nothing here is retyped by hand. */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const SRC = process.env.PROTOTYPE_PATH || resolve(here, '../../calm.ly workforce cc/mockup/calm.ly-workforce-v15.html');
const html = readFileSync(SRC, 'utf8');

/* the block that opens at `start` and closes at its matching brace */
function block(start, from = 0) {
  const i = html.indexOf(start, from);
  if (i < 0) throw new Error('not found: ' + start);
  let depth = 0;
  for (let j = html.indexOf('{', i); j < html.length; j++) {
    if (html[j] === '{') depth++;
    else if (html[j] === '}' && --depth === 0) return { text: html.slice(i, j + 1), end: j + 1 };
  }
  throw new Error('unclosed: ' + start);
}

/* every occurrence of `start`, in case the prototype defines --qp tokens in
   more than one block of the same selector */
function allBlocks(start) {
  const out = [];
  let from = 0;
  for (;;) {
    const i = html.indexOf(start, from);
    if (i < 0) break;
    const { text, end } = block(start, from);
    out.push(text);
    from = end;
  }
  if (out.length === 0) throw new Error('not found: ' + start);
  return out;
}

const out = [
  '/* GENERATED by scripts/lift-tokens.mjs from the prototype. Do not edit by hand.',
  '   Source: ' + SRC.replace(/\\/g, '/').split('/').slice(-3).join('/'),
  '   Run `npm run tokens` to refresh. */',
  ...allBlocks(':root{'),
  ...allBlocks('[data-theme="dark"]{'),
  '',
].join('\n')
  .replace('type — Inter throughout.', 'type — Lexend Deca throughout.')
  .replaceAll('"Inter",system-ui,sans-serif', '"Lexend Deca",system-ui,sans-serif');

mkdirSync(resolve(here, '../src/ui'), { recursive: true });
writeFileSync(resolve(here, '../src/ui/tokens.css'), out);
console.log('tokens.css written:', (out.match(/--qp-[a-z0-9-]+\s*:/g) || []).length, 'definitions');
